spring.application.name=java-api-setup

# custom 404 error page
server.error.whitelabel.enabled=false

# spring jpa configuration

# Prevents the Anti-Pattern of keeping DB connections open during view rendering
spring.jpa.open-in-view=false

# for debugging; you'll see exactly what queries are being executed in the console
spring.jpa.show-sql=true

# use an in-memory database for quick local testing without manual setup
spring.jpa.hibernate.ddl-auto=update

# improves the readability of hibernate logs
spring.jpa.properties.hibernate.format_sql=true

# set static H2 database name so the url dosent change every time
# login at = http://localhost:8080/h2-console
# JDBC URL field = jdbc:h2:mem:example_db
# username = admin
# password = admin

spring.datasource.url=jdbc:h2:mem:example_db

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=admin

spring.datasource.password=admin

# logging configuration
# logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
